<project>
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.jmrtd</groupId>
    <artifactId>jmrtd-parent</artifactId>
    <version>0.5.2</version>
  </parent>
  <artifactId>jj2000_imageio</artifactId>
  <name>JJ2000 ImageIO</name>
  <description>JPEG 2000 image I/O adapter for ImageIO using JJ2000.</description>
<dependencies>
    <dependency>
      <groupId>edu.ucar</groupId>
      <artifactId>jj2000</artifactId>
      <version>5.2</version>
    </dependency>
  </dependencies>
</project>
