<project>
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.jmrtd</groupId>
    <artifactId>jmrtd-parent</artifactId>
    <version>0.5.2</version>
  </parent>
  <artifactId>passportapplet</artifactId>
  <name>Passport Applet</name>
  <description>MRTD Java Card applet.</description>
<dependencies>
    <dependency>
      <groupId>com.klinec</groupId>
      <artifactId>jcardsim</artifactId>
      <version>3.0.6.0</version>
      <scope>provided</scope>
    </dependency>
  </dependencies>
</project>
